# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_Window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QFrame, QGridLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QSpacerItem, QSpinBox,
    QStatusBar, QTabWidget, QTreeWidget, QTreeWidgetItem,
    QWidget)
import Resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1250, 804)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(1250, 804))
        icon = QIcon()
        icon.addFile(u":/Images/Resources/Icons/Full_Amorphous_Toolbox_Logo_Short.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color:  rgb(39, 50, 64);\n"
"color: rgb(225, 225, 225);")
        self.actionAddAdditiveImages = QAction(MainWindow)
        self.actionAddAdditiveImages.setObjectName(u"actionAddAdditiveImages")
        self.actionAddSubtractiveImages = QAction(MainWindow)
        self.actionAddSubtractiveImages.setObjectName(u"actionAddSubtractiveImages")
        self.actionAddMultiplicativeCorrection = QAction(MainWindow)
        self.actionAddMultiplicativeCorrection.setObjectName(u"actionAddMultiplicativeCorrection")
        self.actionRemoveAdditiveImages = QAction(MainWindow)
        self.actionRemoveAdditiveImages.setObjectName(u"actionRemoveAdditiveImages")
        self.actionRemoveSubtractiveImages = QAction(MainWindow)
        self.actionRemoveSubtractiveImages.setObjectName(u"actionRemoveSubtractiveImages")
        self.actionRemoveMultiplicativeCorrection = QAction(MainWindow)
        self.actionRemoveMultiplicativeCorrection.setObjectName(u"actionRemoveMultiplicativeCorrection")
        self.actionAddRotateCCW = QAction(MainWindow)
        self.actionAddRotateCCW.setObjectName(u"actionAddRotateCCW")
        self.actionAddRotateCW = QAction(MainWindow)
        self.actionAddRotateCW.setObjectName(u"actionAddRotateCW")
        self.actionAddSwap = QAction(MainWindow)
        self.actionAddSwap.setObjectName(u"actionAddSwap")
        self.actionSubRotateCCW = QAction(MainWindow)
        self.actionSubRotateCCW.setObjectName(u"actionSubRotateCCW")
        self.actionSubSwap = QAction(MainWindow)
        self.actionSubSwap.setObjectName(u"actionSubSwap")
        self.actionSubRotateCW = QAction(MainWindow)
        self.actionSubRotateCW.setObjectName(u"actionSubRotateCW")
        self.actionMulRotateCCW = QAction(MainWindow)
        self.actionMulRotateCCW.setObjectName(u"actionMulRotateCCW")
        self.actionMulRotateCW = QAction(MainWindow)
        self.actionMulRotateCW.setObjectName(u"actionMulRotateCW")
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionTotalImage = QAction(MainWindow)
        self.actionTotalImage.setObjectName(u"actionTotalImage")
        self.actionCycleImages = QAction(MainWindow)
        self.actionCycleImages.setObjectName(u"actionCycleImages")
        self.actionSingleImages = QAction(MainWindow)
        self.actionSingleImages.setObjectName(u"actionSingleImages")
        self.actionIncrease_Number_of_Cycles = QAction(MainWindow)
        self.actionIncrease_Number_of_Cycles.setObjectName(u"actionIncrease_Number_of_Cycles")
        self.actionDecrease_Number_of_Cycles = QAction(MainWindow)
        self.actionDecrease_Number_of_Cycles.setObjectName(u"actionDecrease_Number_of_Cycles")
        self.actionStartIncreasePadding = QAction(MainWindow)
        self.actionStartIncreasePadding.setObjectName(u"actionStartIncreasePadding")
        self.actionStartDecreasePadding = QAction(MainWindow)
        self.actionStartDecreasePadding.setObjectName(u"actionStartDecreasePadding")
        self.actionEndIncreasePadding = QAction(MainWindow)
        self.actionEndIncreasePadding.setObjectName(u"actionEndIncreasePadding")
        self.actionEndDecreeasePadding = QAction(MainWindow)
        self.actionEndDecreeasePadding.setObjectName(u"actionEndDecreeasePadding")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setMaximumSize(QSize(10000, 10000))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(2, 0, 2, 0)
        self.LowerGridLayout = QGridLayout()
        self.LowerGridLayout.setObjectName(u"LowerGridLayout")
        self.LowerGridLayout.setHorizontalSpacing(6)
        self.LowerGridLayout.setVerticalSpacing(3)
        self.CorrectionFrame = QFrame(self.centralwidget)
        self.CorrectionFrame.setObjectName(u"CorrectionFrame")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.CorrectionFrame.sizePolicy().hasHeightForWidth())
        self.CorrectionFrame.setSizePolicy(sizePolicy2)
        self.CorrectionFrame.setMinimumSize(QSize(475, 123))
        self.CorrectionFrame.setMaximumSize(QSize(475, 123))
        self.CorrectionFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.CorrectionFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.CorrectionFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.CorrectionFrame.setLineWidth(4)
        self.gridLayout_10 = QGridLayout(self.CorrectionFrame)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.MulCorrRotationalSlider = QSlider(self.CorrectionFrame)
        self.MulCorrRotationalSlider.setObjectName(u"MulCorrRotationalSlider")
        self.MulCorrRotationalSlider.setMinimumSize(QSize(80, 23))
        self.MulCorrRotationalSlider.setMaximumSize(QSize(80, 23))
        self.MulCorrRotationalSlider.setMaximum(3)
        self.MulCorrRotationalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.MulCorrRotationalSlider.setTickPosition(QSlider.TickPosition.TicksBelow)

        self.gridLayout_10.addWidget(self.MulCorrRotationalSlider, 2, 3, 1, 1)

        self.MulCorrRightSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.gridLayout_10.addItem(self.MulCorrRightSpacer, 2, 4, 1, 1)

        self.MulRemoveCorrButton = QPushButton(self.CorrectionFrame)
        self.MulRemoveCorrButton.setObjectName(u"MulRemoveCorrButton")
        sizePolicy.setHeightForWidth(self.MulRemoveCorrButton.sizePolicy().hasHeightForWidth())
        self.MulRemoveCorrButton.setSizePolicy(sizePolicy)
        self.MulRemoveCorrButton.setMinimumSize(QSize(50, 23))
        self.MulRemoveCorrButton.setMaximumSize(QSize(50, 23))
        icon1 = QIcon()
        icon1.addFile(u":/Images/Resources/Icons/Remove.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.MulRemoveCorrButton.setIcon(icon1)
        self.MulRemoveCorrButton.setCheckable(True)
        self.MulRemoveCorrButton.setChecked(True)

        self.gridLayout_10.addWidget(self.MulRemoveCorrButton, 2, 1, 1, 1)

        self.MulCorrRotationalLabel = QLabel(self.CorrectionFrame)
        self.MulCorrRotationalLabel.setObjectName(u"MulCorrRotationalLabel")
        self.MulCorrRotationalLabel.setMinimumSize(QSize(30, 23))
        self.MulCorrRotationalLabel.setMaximumSize(QSize(30, 23))
        self.MulCorrRotationalLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_10.addWidget(self.MulCorrRotationalLabel, 2, 5, 1, 1)

        self.MulAddCorrButton = QPushButton(self.CorrectionFrame)
        self.MulAddCorrButton.setObjectName(u"MulAddCorrButton")
        sizePolicy.setHeightForWidth(self.MulAddCorrButton.sizePolicy().hasHeightForWidth())
        self.MulAddCorrButton.setSizePolicy(sizePolicy)
        self.MulAddCorrButton.setMinimumSize(QSize(50, 23))
        self.MulAddCorrButton.setMaximumSize(QSize(50, 23))
        icon2 = QIcon()
        icon2.addFile(u":/Images/Resources/Icons/Add.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.MulAddCorrButton.setIcon(icon2)
        self.MulAddCorrButton.setCheckable(True)

        self.gridLayout_10.addWidget(self.MulAddCorrButton, 2, 0, 1, 1)

        self.MulCorrLeftSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_10.addItem(self.MulCorrLeftSpacer, 2, 2, 1, 1)

        self.MulCorrNameTree = QTreeWidget(self.CorrectionFrame)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"Multiplicative Correction");
        __qtreewidgetitem.setTextAlignment(0, Qt.AlignCenter);
        self.MulCorrNameTree.setHeaderItem(__qtreewidgetitem)
        self.MulCorrNameTree.setObjectName(u"MulCorrNameTree")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.MulCorrNameTree.sizePolicy().hasHeightForWidth())
        self.MulCorrNameTree.setSizePolicy(sizePolicy3)
        self.MulCorrNameTree.setMinimumSize(QSize(475, 100))
        self.MulCorrNameTree.setMaximumSize(QSize(475, 100))
        self.MulCorrNameTree.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.MulCorrNameTree.setFrameShape(QFrame.Shape.StyledPanel)
        self.MulCorrNameTree.setColumnCount(1)

        self.gridLayout_10.addWidget(self.MulCorrNameTree, 0, 0, 1, 6)


        self.LowerGridLayout.addWidget(self.CorrectionFrame, 1, 1, 1, 1)

        self.TotalImageFrame = QFrame(self.centralwidget)
        self.TotalImageFrame.setObjectName(u"TotalImageFrame")
        sizePolicy.setHeightForWidth(self.TotalImageFrame.sizePolicy().hasHeightForWidth())
        self.TotalImageFrame.setSizePolicy(sizePolicy)
        self.TotalImageFrame.setMinimumSize(QSize(350, 250))
        self.TotalImageFrame.setMaximumSize(QSize(350, 250))
        self.TotalImageFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.TotalImageFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.TotalImageFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.TotalImageFrame.setLineWidth(4)
        self.gridLayout_6 = QGridLayout(self.TotalImageFrame)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.TotalImageNameTree = QTreeWidget(self.TotalImageFrame)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setTextAlignment(0, Qt.AlignCenter);
        self.TotalImageNameTree.setHeaderItem(__qtreewidgetitem1)
        self.TotalImageNameTree.setObjectName(u"TotalImageNameTree")
        sizePolicy.setHeightForWidth(self.TotalImageNameTree.sizePolicy().hasHeightForWidth())
        self.TotalImageNameTree.setSizePolicy(sizePolicy)
        self.TotalImageNameTree.setMinimumSize(QSize(0, 0))
        self.TotalImageNameTree.setMaximumSize(QSize(350, 250))
        self.TotalImageNameTree.setStyleSheet(u"background-color: rgb(49, 63, 80);")

        self.gridLayout_6.addWidget(self.TotalImageNameTree, 0, 0, 2, 1)


        self.LowerGridLayout.addWidget(self.TotalImageFrame, 0, 0, 2, 1)

        self.CycleFrame = QFrame(self.centralwidget)
        self.CycleFrame.setObjectName(u"CycleFrame")
        self.CycleFrame.setMinimumSize(QSize(475, 124))
        self.CycleFrame.setMaximumSize(QSize(475, 124))
        self.CycleFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.CycleFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.CycleFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.CycleFrame.setLineWidth(0)
        self.gridLayout_25 = QGridLayout(self.CycleFrame)
        self.gridLayout_25.setObjectName(u"gridLayout_25")
        self.gridLayout_25.setHorizontalSpacing(3)
        self.gridLayout_25.setVerticalSpacing(0)
        self.gridLayout_25.setContentsMargins(0, 2, 0, 0)
        self.DropFirstLabel = QLabel(self.CycleFrame)
        self.DropFirstLabel.setObjectName(u"DropFirstLabel")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.DropFirstLabel.sizePolicy().hasHeightForWidth())
        self.DropFirstLabel.setSizePolicy(sizePolicy4)
        self.DropFirstLabel.setMinimumSize(QSize(59, 23))
        self.DropFirstLabel.setBaseSize(QSize(59, 23))

        self.gridLayout_25.addWidget(self.DropFirstLabel, 2, 0, 1, 1)

        self.DropFirstBox = QSpinBox(self.CycleFrame)
        self.DropFirstBox.setObjectName(u"DropFirstBox")
        self.DropFirstBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DropFirstBox.setMaximum(100000)

        self.gridLayout_25.addWidget(self.DropFirstBox, 2, 1, 1, 1)

        self.CyclesBox = QSpinBox(self.CycleFrame)
        self.CyclesBox.setObjectName(u"CyclesBox")
        self.CyclesBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CyclesBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.CyclesBox.setMinimum(1)
        self.CyclesBox.setMaximum(100000)

        self.gridLayout_25.addWidget(self.CyclesBox, 1, 1, 1, 1)

        self.CycleHeaderTree = QTreeWidget(self.CycleFrame)
        __qtreewidgetitem2 = QTreeWidgetItem()
        __qtreewidgetitem2.setTextAlignment(0, Qt.AlignCenter);
        self.CycleHeaderTree.setHeaderItem(__qtreewidgetitem2)
        self.CycleHeaderTree.setObjectName(u"CycleHeaderTree")
        self.CycleHeaderTree.setMinimumSize(QSize(471, 0))
        self.CycleHeaderTree.setMaximumSize(QSize(474, 23))
        self.CycleHeaderTree.setFrameShape(QFrame.Shape.NoFrame)
        self.CycleHeaderTree.setExpandsOnDoubleClick(False)

        self.gridLayout_25.addWidget(self.CycleHeaderTree, 0, 0, 1, 3)

        self.CyclesLabel = QLabel(self.CycleFrame)
        self.CyclesLabel.setObjectName(u"CyclesLabel")
        sizePolicy4.setHeightForWidth(self.CyclesLabel.sizePolicy().hasHeightForWidth())
        self.CyclesLabel.setSizePolicy(sizePolicy4)
        self.CyclesLabel.setMinimumSize(QSize(59, 23))
        self.CyclesLabel.setBaseSize(QSize(59, 23))

        self.gridLayout_25.addWidget(self.CyclesLabel, 1, 0, 1, 1)

        self.DropLastBox = QSpinBox(self.CycleFrame)
        self.DropLastBox.setObjectName(u"DropLastBox")
        self.DropLastBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.DropLastBox.setMaximum(100000)

        self.gridLayout_25.addWidget(self.DropLastBox, 2, 2, 1, 1)


        self.LowerGridLayout.addWidget(self.CycleFrame, 0, 1, 1, 1)

        self.CompilerFrame = QFrame(self.centralwidget)
        self.CompilerFrame.setObjectName(u"CompilerFrame")
        self.CompilerFrame.setMinimumSize(QSize(407, 250))
        self.CompilerFrame.setMaximumSize(QSize(407, 250))
        self.CompilerFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.CompilerFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.CompilerFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.CompilerFrame.setLineWidth(4)
        self.gridLayout_26 = QGridLayout(self.CompilerFrame)
        self.gridLayout_26.setObjectName(u"gridLayout_26")
        self.gridLayout_26.setHorizontalSpacing(1)
        self.gridLayout_26.setVerticalSpacing(0)
        self.gridLayout_26.setContentsMargins(0, 1, 0, 0)
        self.FileProgressBar = QProgressBar(self.CompilerFrame)
        self.FileProgressBar.setObjectName(u"FileProgressBar")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.FileProgressBar.sizePolicy().hasHeightForWidth())
        self.FileProgressBar.setSizePolicy(sizePolicy5)
        self.FileProgressBar.setValue(0)

        self.gridLayout_26.addWidget(self.FileProgressBar, 5, 1, 1, 3)

        self.CompilerHeaderTree = QTreeWidget(self.CompilerFrame)
        __qtreewidgetitem3 = QTreeWidgetItem()
        __qtreewidgetitem3.setTextAlignment(0, Qt.AlignCenter);
        self.CompilerHeaderTree.setHeaderItem(__qtreewidgetitem3)
        self.CompilerHeaderTree.setObjectName(u"CompilerHeaderTree")
        sizePolicy3.setHeightForWidth(self.CompilerHeaderTree.sizePolicy().hasHeightForWidth())
        self.CompilerHeaderTree.setSizePolicy(sizePolicy3)
        self.CompilerHeaderTree.setMinimumSize(QSize(0, 23))
        self.CompilerHeaderTree.setMaximumSize(QSize(16777215, 23))
        self.CompilerHeaderTree.setFrameShape(QFrame.Shape.NoFrame)

        self.gridLayout_26.addWidget(self.CompilerHeaderTree, 0, 0, 1, 5)

        self.LoadFolderButton = QPushButton(self.CompilerFrame)
        self.LoadFolderButton.setObjectName(u"LoadFolderButton")
        sizePolicy.setHeightForWidth(self.LoadFolderButton.sizePolicy().hasHeightForWidth())
        self.LoadFolderButton.setSizePolicy(sizePolicy)
        self.LoadFolderButton.setMinimumSize(QSize(25, 23))
        self.LoadFolderButton.setMaximumSize(QSize(25, 16777215))
        self.LoadFolderButton.setBaseSize(QSize(0, 0))
        icon3 = QIcon()
        icon3.addFile(u":/Images/Resources/Icons/Load.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.LoadFolderButton.setIcon(icon3)

        self.gridLayout_26.addWidget(self.LoadFolderButton, 1, 4, 1, 1)

        self.SaveTotalButton = QPushButton(self.CompilerFrame)
        self.SaveTotalButton.setObjectName(u"SaveTotalButton")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.SaveTotalButton.sizePolicy().hasHeightForWidth())
        self.SaveTotalButton.setSizePolicy(sizePolicy6)
        self.SaveTotalButton.setMinimumSize(QSize(100, 23))
        self.SaveTotalButton.setMaximumSize(QSize(16777215, 16777215))
        self.SaveTotalButton.setBaseSize(QSize(0, 0))
        icon4 = QIcon()
        icon4.addFile(u":/Images/Resources/Icons/Compile.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.SaveTotalButton.setIcon(icon4)

        self.gridLayout_26.addWidget(self.SaveTotalButton, 3, 1, 1, 1)

        self.label_4 = QLabel(self.CompilerFrame)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout_26.addWidget(self.label_4, 5, 0, 1, 1)

        self.label_2 = QLabel(self.CompilerFrame)
        self.label_2.setObjectName(u"label_2")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy7)

        self.gridLayout_26.addWidget(self.label_2, 1, 0, 1, 1)

        self.FolderBox = QLineEdit(self.CompilerFrame)
        self.FolderBox.setObjectName(u"FolderBox")
        sizePolicy5.setHeightForWidth(self.FolderBox.sizePolicy().hasHeightForWidth())
        self.FolderBox.setSizePolicy(sizePolicy5)
        self.FolderBox.setMinimumSize(QSize(0, 23))
        self.FolderBox.setBaseSize(QSize(256, 23))

        self.gridLayout_26.addWidget(self.FolderBox, 1, 1, 1, 3)

        self.NameBox = QLineEdit(self.CompilerFrame)
        self.NameBox.setObjectName(u"NameBox")
        sizePolicy5.setHeightForWidth(self.NameBox.sizePolicy().hasHeightForWidth())
        self.NameBox.setSizePolicy(sizePolicy5)
        self.NameBox.setMinimumSize(QSize(0, 23))
        self.NameBox.setBaseSize(QSize(256, 23))

        self.gridLayout_26.addWidget(self.NameBox, 2, 1, 1, 3)

        self.label_3 = QLabel(self.CompilerFrame)
        self.label_3.setObjectName(u"label_3")
        sizePolicy7.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy7)

        self.gridLayout_26.addWidget(self.label_3, 2, 0, 1, 1)

        self.SaveCyclesButton = QPushButton(self.CompilerFrame)
        self.SaveCyclesButton.setObjectName(u"SaveCyclesButton")
        sizePolicy6.setHeightForWidth(self.SaveCyclesButton.sizePolicy().hasHeightForWidth())
        self.SaveCyclesButton.setSizePolicy(sizePolicy6)
        self.SaveCyclesButton.setMinimumSize(QSize(100, 23))
        self.SaveCyclesButton.setMaximumSize(QSize(16777215, 16777215))
        self.SaveCyclesButton.setBaseSize(QSize(0, 0))
        icon5 = QIcon()
        icon5.addFile(u":/Images/Resources/Icons/Stack.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.SaveCyclesButton.setIcon(icon5)
        self.SaveCyclesButton.setCheckable(False)
        self.SaveCyclesButton.setChecked(False)

        self.gridLayout_26.addWidget(self.SaveCyclesButton, 3, 2, 1, 1)

        self.label = QLabel(self.CompilerFrame)
        self.label.setObjectName(u"label")
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)
        self.label.setMaximumSize(QSize(50, 16777215))

        self.gridLayout_26.addWidget(self.label, 3, 0, 1, 1)

        self.SaveSinglesButton = QPushButton(self.CompilerFrame)
        self.SaveSinglesButton.setObjectName(u"SaveSinglesButton")
        sizePolicy6.setHeightForWidth(self.SaveSinglesButton.sizePolicy().hasHeightForWidth())
        self.SaveSinglesButton.setSizePolicy(sizePolicy6)
        self.SaveSinglesButton.setMinimumSize(QSize(100, 23))
        self.SaveSinglesButton.setMaximumSize(QSize(16777215, 16777215))
        icon6 = QIcon()
        icon6.addFile(u":/Images/Resources/Icons/Single.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.SaveSinglesButton.setIcon(icon6)

        self.gridLayout_26.addWidget(self.SaveSinglesButton, 3, 3, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 65, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.gridLayout_26.addItem(self.verticalSpacer, 4, 0, 1, 1)


        self.LowerGridLayout.addWidget(self.CompilerFrame, 0, 2, 2, 1)


        self.gridLayout.addLayout(self.LowerGridLayout, 1, 0, 1, 2)

        self.UpperGridLayout = QGridLayout()
        self.UpperGridLayout.setObjectName(u"UpperGridLayout")
        self.SubPlotFrame = QFrame(self.centralwidget)
        self.SubPlotFrame.setObjectName(u"SubPlotFrame")
        sizePolicy4.setHeightForWidth(self.SubPlotFrame.sizePolicy().hasHeightForWidth())
        self.SubPlotFrame.setSizePolicy(sizePolicy4)
        self.SubPlotFrame.setMinimumSize(QSize(475, 250))
        self.SubPlotFrame.setMaximumSize(QSize(475, 250))
        self.SubPlotFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.SubPlotFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.SubPlotFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.SubPlotFrame.setLineWidth(4)
        self.gridLayout_9 = QGridLayout(self.SubPlotFrame)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(1, 1, 1, 1)
        self.SubNormMatplotFrame = QFrame(self.SubPlotFrame)
        self.SubNormMatplotFrame.setObjectName(u"SubNormMatplotFrame")
        sizePolicy.setHeightForWidth(self.SubNormMatplotFrame.sizePolicy().hasHeightForWidth())
        self.SubNormMatplotFrame.setSizePolicy(sizePolicy)
        self.SubNormMatplotFrame.setMinimumSize(QSize(471, 246))
        self.SubNormMatplotFrame.setMaximumSize(QSize(471, 246))
        self.SubNormMatplotFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.SubNormMatplotFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.SubNormMatplotFrame.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout_9.addWidget(self.SubNormMatplotFrame, 0, 1, 1, 2)


        self.UpperGridLayout.addWidget(self.SubPlotFrame, 1, 1, 1, 1)

        self.SubImageFrame = QFrame(self.centralwidget)
        self.SubImageFrame.setObjectName(u"SubImageFrame")
        sizePolicy4.setHeightForWidth(self.SubImageFrame.sizePolicy().hasHeightForWidth())
        self.SubImageFrame.setSizePolicy(sizePolicy4)
        self.SubImageFrame.setMinimumSize(QSize(0, 0))
        self.SubImageFrame.setMaximumSize(QSize(350, 250))
        self.SubImageFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.SubImageFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.SubImageFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.SubImageFrame.setLineWidth(4)
        self.gridLayout_7 = QGridLayout(self.SubImageFrame)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.SubRotationalSlider = QSlider(self.SubImageFrame)
        self.SubRotationalSlider.setObjectName(u"SubRotationalSlider")
        self.SubRotationalSlider.setMinimumSize(QSize(80, 23))
        self.SubRotationalSlider.setMaximumSize(QSize(80, 23))
        self.SubRotationalSlider.setMaximum(3)
        self.SubRotationalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.SubRotationalSlider.setTickPosition(QSlider.TickPosition.TicksBelow)

        self.gridLayout_7.addWidget(self.SubRotationalSlider, 1, 4, 1, 1)

        self.SubRightSpacer = QSpacerItem(100, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_7.addItem(self.SubRightSpacer, 1, 3, 1, 1)

        self.SubLeftSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_7.addItem(self.SubLeftSpacer, 1, 5, 1, 1)

        self.SubAddSetButton = QPushButton(self.SubImageFrame)
        self.SubAddSetButton.setObjectName(u"SubAddSetButton")
        sizePolicy.setHeightForWidth(self.SubAddSetButton.sizePolicy().hasHeightForWidth())
        self.SubAddSetButton.setSizePolicy(sizePolicy)
        self.SubAddSetButton.setMinimumSize(QSize(50, 23))
        self.SubAddSetButton.setMaximumSize(QSize(50, 23))
        self.SubAddSetButton.setIcon(icon2)
        self.SubAddSetButton.setCheckable(True)

        self.gridLayout_7.addWidget(self.SubAddSetButton, 1, 1, 1, 1)

        self.SubRotationalLabel = QLabel(self.SubImageFrame)
        self.SubRotationalLabel.setObjectName(u"SubRotationalLabel")
        self.SubRotationalLabel.setMinimumSize(QSize(30, 23))
        self.SubRotationalLabel.setMaximumSize(QSize(30, 23))
        self.SubRotationalLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_7.addWidget(self.SubRotationalLabel, 1, 6, 1, 1)

        self.SubImageNameTree = QTreeWidget(self.SubImageFrame)
        __qtreewidgetitem4 = QTreeWidgetItem()
        __qtreewidgetitem4.setTextAlignment(0, Qt.AlignCenter);
        self.SubImageNameTree.setHeaderItem(__qtreewidgetitem4)
        self.SubImageNameTree.setObjectName(u"SubImageNameTree")
        sizePolicy.setHeightForWidth(self.SubImageNameTree.sizePolicy().hasHeightForWidth())
        self.SubImageNameTree.setSizePolicy(sizePolicy)
        self.SubImageNameTree.setMinimumSize(QSize(0, 0))
        self.SubImageNameTree.setMaximumSize(QSize(346, 346))
        self.SubImageNameTree.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.SubImageNameTree.setHeaderHidden(False)
        self.SubImageNameTree.header().setVisible(True)

        self.gridLayout_7.addWidget(self.SubImageNameTree, 0, 0, 1, 9)

        self.SubRemoveSetButton = QPushButton(self.SubImageFrame)
        self.SubRemoveSetButton.setObjectName(u"SubRemoveSetButton")
        sizePolicy.setHeightForWidth(self.SubRemoveSetButton.sizePolicy().hasHeightForWidth())
        self.SubRemoveSetButton.setSizePolicy(sizePolicy)
        self.SubRemoveSetButton.setMinimumSize(QSize(50, 23))
        self.SubRemoveSetButton.setMaximumSize(QSize(50, 23))
        self.SubRemoveSetButton.setIcon(icon1)
        self.SubRemoveSetButton.setCheckable(True)
        self.SubRemoveSetButton.setChecked(True)

        self.gridLayout_7.addWidget(self.SubRemoveSetButton, 1, 2, 1, 1)

        self.SubSwapSetButton = QPushButton(self.SubImageFrame)
        self.SubSwapSetButton.setObjectName(u"SubSwapSetButton")
        self.SubSwapSetButton.setMinimumSize(QSize(25, 23))
        self.SubSwapSetButton.setMaximumSize(QSize(25, 23))
        icon7 = QIcon()
        icon7.addFile(u":/Images/Resources/Icons/Swap.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.SubSwapSetButton.setIcon(icon7)

        self.gridLayout_7.addWidget(self.SubSwapSetButton, 1, 7, 1, 1)


        self.UpperGridLayout.addWidget(self.SubImageFrame, 1, 0, 1, 1)

        self.AddPlotFrame = QFrame(self.centralwidget)
        self.AddPlotFrame.setObjectName(u"AddPlotFrame")
        sizePolicy4.setHeightForWidth(self.AddPlotFrame.sizePolicy().hasHeightForWidth())
        self.AddPlotFrame.setSizePolicy(sizePolicy4)
        self.AddPlotFrame.setMinimumSize(QSize(475, 250))
        self.AddPlotFrame.setMaximumSize(QSize(475, 250))
        self.AddPlotFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.AddPlotFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.AddPlotFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.AddPlotFrame.setLineWidth(4)
        self.gridLayout_3 = QGridLayout(self.AddPlotFrame)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.AddNormMatplotFrame = QFrame(self.AddPlotFrame)
        self.AddNormMatplotFrame.setObjectName(u"AddNormMatplotFrame")
        sizePolicy.setHeightForWidth(self.AddNormMatplotFrame.sizePolicy().hasHeightForWidth())
        self.AddNormMatplotFrame.setSizePolicy(sizePolicy)
        self.AddNormMatplotFrame.setMinimumSize(QSize(471, 246))
        self.AddNormMatplotFrame.setMaximumSize(QSize(471, 246))
        self.AddNormMatplotFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.AddNormMatplotFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.AddNormMatplotFrame.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout_3.addWidget(self.AddNormMatplotFrame, 0, 0, 1, 2)


        self.UpperGridLayout.addWidget(self.AddPlotFrame, 0, 1, 1, 1)

        self.AddImageFrame = QFrame(self.centralwidget)
        self.AddImageFrame.setObjectName(u"AddImageFrame")
        sizePolicy4.setHeightForWidth(self.AddImageFrame.sizePolicy().hasHeightForWidth())
        self.AddImageFrame.setSizePolicy(sizePolicy4)
        self.AddImageFrame.setMinimumSize(QSize(0, 0))
        self.AddImageFrame.setMaximumSize(QSize(350, 250))
        self.AddImageFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.AddImageFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.AddImageFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.AddImageFrame.setLineWidth(4)
        self.gridLayout_2 = QGridLayout(self.AddImageFrame)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.AddHorizontalSpacer = QSpacerItem(100, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.AddHorizontalSpacer, 1, 2, 1, 1)

        self.AddSwapSetButton = QPushButton(self.AddImageFrame)
        self.AddSwapSetButton.setObjectName(u"AddSwapSetButton")
        self.AddSwapSetButton.setMinimumSize(QSize(25, 23))
        self.AddSwapSetButton.setMaximumSize(QSize(25, 23))
        self.AddSwapSetButton.setIcon(icon7)

        self.gridLayout_2.addWidget(self.AddSwapSetButton, 1, 6, 1, 1)

        self.AddRotationalLabel = QLabel(self.AddImageFrame)
        self.AddRotationalLabel.setObjectName(u"AddRotationalLabel")
        self.AddRotationalLabel.setMinimumSize(QSize(30, 23))
        self.AddRotationalLabel.setMaximumSize(QSize(30, 23))
        self.AddRotationalLabel.setBaseSize(QSize(0, 0))
        self.AddRotationalLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.AddRotationalLabel, 1, 5, 1, 1)

        self.AddRemoveSetButton = QPushButton(self.AddImageFrame)
        self.AddRemoveSetButton.setObjectName(u"AddRemoveSetButton")
        sizePolicy.setHeightForWidth(self.AddRemoveSetButton.sizePolicy().hasHeightForWidth())
        self.AddRemoveSetButton.setSizePolicy(sizePolicy)
        self.AddRemoveSetButton.setMinimumSize(QSize(50, 23))
        self.AddRemoveSetButton.setMaximumSize(QSize(23, 23))
        self.AddRemoveSetButton.setIcon(icon1)
        self.AddRemoveSetButton.setCheckable(True)
        self.AddRemoveSetButton.setChecked(True)

        self.gridLayout_2.addWidget(self.AddRemoveSetButton, 1, 1, 1, 1)

        self.AddAddSetButton = QPushButton(self.AddImageFrame)
        self.AddAddSetButton.setObjectName(u"AddAddSetButton")
        sizePolicy.setHeightForWidth(self.AddAddSetButton.sizePolicy().hasHeightForWidth())
        self.AddAddSetButton.setSizePolicy(sizePolicy)
        self.AddAddSetButton.setMinimumSize(QSize(50, 23))
        self.AddAddSetButton.setMaximumSize(QSize(23, 23))
        self.AddAddSetButton.setIcon(icon2)
        self.AddAddSetButton.setCheckable(True)

        self.gridLayout_2.addWidget(self.AddAddSetButton, 1, 0, 1, 1)

        self.AddRotationalSlider = QSlider(self.AddImageFrame)
        self.AddRotationalSlider.setObjectName(u"AddRotationalSlider")
        sizePolicy.setHeightForWidth(self.AddRotationalSlider.sizePolicy().hasHeightForWidth())
        self.AddRotationalSlider.setSizePolicy(sizePolicy)
        self.AddRotationalSlider.setMinimumSize(QSize(80, 23))
        self.AddRotationalSlider.setMaximumSize(QSize(80, 23))
        self.AddRotationalSlider.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.AddRotationalSlider.setMaximum(3)
        self.AddRotationalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.AddRotationalSlider.setTickPosition(QSlider.TickPosition.TicksBelow)

        self.gridLayout_2.addWidget(self.AddRotationalSlider, 1, 3, 1, 1)

        self.AddRightSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.AddRightSpacer, 1, 4, 1, 1)

        self.AddImageNameTree = QTreeWidget(self.AddImageFrame)
        __qtreewidgetitem5 = QTreeWidgetItem()
        __qtreewidgetitem5.setTextAlignment(0, Qt.AlignCenter);
        self.AddImageNameTree.setHeaderItem(__qtreewidgetitem5)
        self.AddImageNameTree.setObjectName(u"AddImageNameTree")
        sizePolicy.setHeightForWidth(self.AddImageNameTree.sizePolicy().hasHeightForWidth())
        self.AddImageNameTree.setSizePolicy(sizePolicy)
        self.AddImageNameTree.setMinimumSize(QSize(0, 0))
        self.AddImageNameTree.setMaximumSize(QSize(346, 223))
        self.AddImageNameTree.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.AddImageNameTree.setHeaderHidden(False)
        self.AddImageNameTree.header().setVisible(True)

        self.gridLayout_2.addWidget(self.AddImageNameTree, 0, 0, 1, 8)


        self.UpperGridLayout.addWidget(self.AddImageFrame, 0, 0, 1, 1)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy2.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy2)
        self.frame.setMinimumSize(QSize(407, 506))
        self.frame.setMaximumSize(QSize(407, 506))
        self.frame.setStyleSheet(u"background-color: rgb(49, 63, 80);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.frame)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pixmapTabs = QTabWidget(self.frame)
        self.pixmapTabs.setObjectName(u"pixmapTabs")
        sizePolicy2.setHeightForWidth(self.pixmapTabs.sizePolicy().hasHeightForWidth())
        self.pixmapTabs.setSizePolicy(sizePolicy2)
        self.pixmapTabs.setMinimumSize(QSize(405, 504))
        self.pixmapTabs.setMaximumSize(QSize(405, 504))
        self.pixmapTabs.setStyleSheet(u"background-color: rgb(49, 63, 80);\n"
"border-color: rgb(0, 0, 0);")
        self.pixmapTabs.setTabPosition(QTabWidget.TabPosition.South)
        self.pixmapTabs.setTabsClosable(False)
        self.pixmapTabs.setTabBarAutoHide(False)
        self.Image = QWidget()
        self.Image.setObjectName(u"Image")
        sizePolicy2.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy2)
        self.Image.setMinimumSize(QSize(405, 477))
        self.Image.setMaximumSize(QSize(405, 477))
        self.Image.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.gridLayout_5 = QGridLayout(self.Image)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.imagematplotFrame = QFrame(self.Image)
        self.imagematplotFrame.setObjectName(u"imagematplotFrame")
        sizePolicy.setHeightForWidth(self.imagematplotFrame.sizePolicy().hasHeightForWidth())
        self.imagematplotFrame.setSizePolicy(sizePolicy)
        self.imagematplotFrame.setMinimumSize(QSize(401, 471))
        self.imagematplotFrame.setMaximumSize(QSize(401, 471))
        self.imagematplotFrame.setStyleSheet(u"background-color: rgb(49, 63, 80);\n"
"")
        self.imagematplotFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.imagematplotFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.imagematplotFrame.setLineWidth(0)

        self.gridLayout_5.addWidget(self.imagematplotFrame, 0, 0, 1, 1)

        self.pixmapTabs.addTab(self.Image, "")

        self.gridLayout_4.addWidget(self.pixmapTabs, 0, 1, 1, 1)


        self.UpperGridLayout.addWidget(self.frame, 0, 2, 2, 1)


        self.gridLayout.addLayout(self.UpperGridLayout, 0, 0, 1, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1250, 19))
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuAddImages = QMenu(self.menuFile)
        self.menuAddImages.setObjectName(u"menuAddImages")
        self.menuRemoveImages = QMenu(self.menuFile)
        self.menuRemoveImages.setObjectName(u"menuRemoveImages")
        self.menuSaveImages = QMenu(self.menuFile)
        self.menuSaveImages.setObjectName(u"menuSaveImages")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.menuAddImages.menuAction())
        self.menuFile.addAction(self.menuRemoveImages.menuAction())
        self.menuFile.addAction(self.menuSaveImages.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAddImages.addAction(self.actionAddAdditiveImages)
        self.menuAddImages.addAction(self.actionAddSubtractiveImages)
        self.menuAddImages.addAction(self.actionAddMultiplicativeCorrection)
        self.menuRemoveImages.addAction(self.actionRemoveAdditiveImages)
        self.menuRemoveImages.addAction(self.actionRemoveSubtractiveImages)
        self.menuRemoveImages.addAction(self.actionRemoveMultiplicativeCorrection)
        self.menuSaveImages.addAction(self.actionTotalImage)
        self.menuSaveImages.addAction(self.actionCycleImages)
        self.menuSaveImages.addAction(self.actionSingleImages)

        self.retranslateUi(MainWindow)

        self.pixmapTabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Amorphous Toolbox - Image Compiler Tool", None))
        self.actionAddAdditiveImages.setText(QCoreApplication.translate("MainWindow", u"Additive Images", None))
        self.actionAddSubtractiveImages.setText(QCoreApplication.translate("MainWindow", u"Subtractive Images", None))
        self.actionAddMultiplicativeCorrection.setText(QCoreApplication.translate("MainWindow", u"Multiplicative Correction", None))
        self.actionRemoveAdditiveImages.setText(QCoreApplication.translate("MainWindow", u"Additive Images", None))
        self.actionRemoveSubtractiveImages.setText(QCoreApplication.translate("MainWindow", u"Subtractive Images", None))
        self.actionRemoveMultiplicativeCorrection.setText(QCoreApplication.translate("MainWindow", u"Multiplicative Correction", None))
        self.actionAddRotateCCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CCW 90\u00b0", None))
        self.actionAddRotateCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CW 90\u00b0", None))
        self.actionAddSwap.setText(QCoreApplication.translate("MainWindow", u"Swap", None))
        self.actionSubRotateCCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CCW 90\u00b0", None))
        self.actionSubSwap.setText(QCoreApplication.translate("MainWindow", u"Swap", None))
        self.actionSubRotateCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CW 90\u00b0", None))
        self.actionMulRotateCCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CCW 90\u00b0", None))
        self.actionMulRotateCW.setText(QCoreApplication.translate("MainWindow", u"Rotate CW 90\u00b0", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"User Preferences", None))
        self.actionTotalImage.setText(QCoreApplication.translate("MainWindow", u"Compile Image - Total", None))
        self.actionCycleImages.setText(QCoreApplication.translate("MainWindow", u"Compile Image Collection - Cycles", None))
        self.actionSingleImages.setText(QCoreApplication.translate("MainWindow", u"Compile Image Collection - Individuals", None))
        self.actionIncrease_Number_of_Cycles.setText(QCoreApplication.translate("MainWindow", u"Increase Number of Cycles", None))
        self.actionDecrease_Number_of_Cycles.setText(QCoreApplication.translate("MainWindow", u"Decrease Number of Cycles", None))
        self.actionStartIncreasePadding.setText(QCoreApplication.translate("MainWindow", u"Increase Padding", None))
        self.actionStartDecreasePadding.setText(QCoreApplication.translate("MainWindow", u"Decrease Padding", None))
        self.actionEndIncreasePadding.setText(QCoreApplication.translate("MainWindow", u"Increase Padding", None))
        self.actionEndDecreeasePadding.setText(QCoreApplication.translate("MainWindow", u"Decreease Padding", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About Us", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(tooltip)
        self.MulCorrRotationalSlider.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate the multiplicative correction image.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.MulRemoveCorrButton.setToolTip(QCoreApplication.translate("MainWindow", u"Remove a multiplicative correction image.", None))
#endif // QT_CONFIG(tooltip)
        self.MulRemoveCorrButton.setText("")
        self.MulCorrRotationalLabel.setText(QCoreApplication.translate("MainWindow", u"0\u00b0", None))
#if QT_CONFIG(tooltip)
        self.MulAddCorrButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add a multiplicative correction image.", None))
#endif // QT_CONFIG(tooltip)
        self.MulAddCorrButton.setText("")
        ___qtreewidgetitem = self.TotalImageNameTree.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Total Images", None));
        self.DropFirstLabel.setText(QCoreApplication.translate("MainWindow", u" Drop:", None))
#if QT_CONFIG(tooltip)
        self.DropFirstBox.setToolTip(QCoreApplication.translate("MainWindow", u"Drop the first (N) images of each cycle.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.CyclesBox.setToolTip(QCoreApplication.translate("MainWindow", u"Seperate all images into (N) cycles.", None))
#endif // QT_CONFIG(tooltip)
        ___qtreewidgetitem1 = self.CycleHeaderTree.headerItem()
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Cycle Control", None));
        self.CyclesLabel.setText(QCoreApplication.translate("MainWindow", u" Cycles:", None))
#if QT_CONFIG(tooltip)
        self.DropLastBox.setToolTip(QCoreApplication.translate("MainWindow", u"Drop the Last (N) images of each cycle.", None))
#endif // QT_CONFIG(tooltip)
        ___qtreewidgetitem2 = self.CompilerHeaderTree.headerItem()
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Compiler Control", None));
#if QT_CONFIG(tooltip)
        self.LoadFolderButton.setToolTip(QCoreApplication.translate("MainWindow", u"Load the output folder path.", None))
#endif // QT_CONFIG(tooltip)
        self.LoadFolderButton.setText("")
#if QT_CONFIG(tooltip)
        self.SaveTotalButton.setToolTip(QCoreApplication.translate("MainWindow", u"Compile all images and cycles into a single image.", None))
#endif // QT_CONFIG(tooltip)
        self.SaveTotalButton.setText(QCoreApplication.translate("MainWindow", u"Total", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u" Progress: ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u" Folder:", None))
        self.FolderBox.setText("")
        self.FolderBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Output File Folder", None))
        self.NameBox.setText("")
        self.NameBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Output File Name", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u" Name:", None))
#if QT_CONFIG(tooltip)
        self.SaveCyclesButton.setToolTip(QCoreApplication.translate("MainWindow", u"Compile all cycles into indivdual images.", None))
#endif // QT_CONFIG(tooltip)
        self.SaveCyclesButton.setText(QCoreApplication.translate("MainWindow", u"Cycles", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u" Save:", None))
#if QT_CONFIG(tooltip)
        self.SaveSinglesButton.setToolTip(QCoreApplication.translate("MainWindow", u"Compile all images indivdually.", None))
#endif // QT_CONFIG(tooltip)
        self.SaveSinglesButton.setText(QCoreApplication.translate("MainWindow", u"Individuals", None))
#if QT_CONFIG(tooltip)
        self.SubRotationalSlider.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate subtractive images.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.SubAddSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add subtractive images.", None))
#endif // QT_CONFIG(tooltip)
        self.SubAddSetButton.setText("")
        self.SubRotationalLabel.setText(QCoreApplication.translate("MainWindow", u"0\u00b0", None))
        ___qtreewidgetitem3 = self.SubImageNameTree.headerItem()
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"Subtractive Images", None));
#if QT_CONFIG(tooltip)
        self.SubRemoveSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Remove subtractive images.", None))
#endif // QT_CONFIG(tooltip)
        self.SubRemoveSetButton.setText("")
#if QT_CONFIG(tooltip)
        self.SubSwapSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Swap additive and subtractive images.", None))
#endif // QT_CONFIG(tooltip)
        self.SubSwapSetButton.setText("")
#if QT_CONFIG(tooltip)
        self.AddSwapSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Swap additive and subtractive images.", None))
#endif // QT_CONFIG(tooltip)
        self.AddSwapSetButton.setText("")
        self.AddRotationalLabel.setText(QCoreApplication.translate("MainWindow", u"0\u00b0", None))
#if QT_CONFIG(tooltip)
        self.AddRemoveSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Remove additive images.", None))
#endif // QT_CONFIG(tooltip)
        self.AddRemoveSetButton.setText("")
#if QT_CONFIG(tooltip)
        self.AddAddSetButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add additive images.", None))
#endif // QT_CONFIG(tooltip)
        self.AddAddSetButton.setText("")
#if QT_CONFIG(tooltip)
        self.AddRotationalSlider.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate additive images.", None))
#endif // QT_CONFIG(tooltip)
        ___qtreewidgetitem4 = self.AddImageNameTree.headerItem()
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"Additive Images", None));
        self.pixmapTabs.setTabText(self.pixmapTabs.indexOf(self.Image), QCoreApplication.translate("MainWindow", u"Image", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuAddImages.setTitle(QCoreApplication.translate("MainWindow", u"Load Images", None))
        self.menuRemoveImages.setTitle(QCoreApplication.translate("MainWindow", u"Remove Images", None))
        self.menuSaveImages.setTitle(QCoreApplication.translate("MainWindow", u"Save Images", None))
    # retranslateUi

